In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_json("../arquivosCSV/receitas.json", encoding="utf8")
dataframe

                                            receitas
0  {'titulo': 'Bolo de Chocolate', 'tempo_preparo...
1  {'titulo': 'Salada', 'tempo_preparo': '20 Minu...
2  {'titulo': 'Salada Familia', 'tempo_preparo': ...

In [3]:
dataframe_receitas = pd.json_normalize(
    dataframe['receitas'],
    'ingredientes',
    ['titulo', 'tempo_preparo', 'porcoes']
)
dataframe_receitas

        ingrediente  Quantidade             titulo tempo_preparo porcoes
0  Farinha de Trigo   2 xicaras  Bolo de Chocolate    45 Minutos       8
0            Acucar    1 xicara  Bolo de Chocolate    45 Minutos       8
0              Ovos   3 xicaras  Bolo de Chocolate    45 Minutos       8
0             Leite    1 xicara  Bolo de Chocolate    45 Minutos       8
0          Manteiga  1/2 xicara  Bolo de Chocolate    45 Minutos       8
1     Alface Romana    1 cabeca             Salada    20 Minutos       4
1          Croutons    1 xicara             Salada    20 Minutos       4
1   Queijo Parmesao  1/2 xicara             Salada    20 Minutos       4
1             Molho  1/4 xicara             Salada    20 Minutos       4
2     Alface Romana    2 cabeca     Salada Familia    40 Minutos       8
2          Croutons    2 xicara     Salada Familia    40 Minutos       8
2   Queijo Parmesao    1 xicara     Salada Familia    40 Minutos       8
2             Molho  1/2 xicara     Salada Familia    40 Minutos       8