In [1]:
import pandas as pd

In [3]:
dataframe = pd.read_json("../arquivosCSV/receitas.json", encoding="utf8")
dataframe

                                            receitas
0  {'titulo': 'Bolo de Chocolate', 'tempo_preparo...
1  {'titulo': 'Salada', 'tempo_preparo': '20 Minu...
2  {'titulo': 'Salada Familia', 'tempo_preparo': ...

In [6]:
# Analise -> Total de ingredientes por receita
receitas_expandidas = []
for receita in dataframe['receitas']:
    total_ingredientes_por_receita = len(receita['ingredientes'])
    receita_informacoes = {
        'titulo': receita['titulo'],
        'tempo_preparo': receita['tempo_preparo'],
        'porcoes': receita['porcoes'],
        'total_ingredientes': total_ingredientes_por_receita
    }
    receitas_expandidas.append(receita_informacoes)

In [7]:
receitas_expandidas

[{'titulo': 'Bolo de Chocolate',
  'tempo_preparo': '45 Minutos',
  'porcoes': 8,
  'total_ingredientes': 5},
 {'titulo': 'Salada',
  'tempo_preparo': '20 Minutos',
  'porcoes': 4,
  'total_ingredientes': 4},
 {'titulo': 'Salada Familia',
  'tempo_preparo': '40 Minutos',
  'porcoes': 8,
  'total_ingredientes': 4}]

In [8]:
dataframe_expandido = pd.DataFrame(receitas_expandidas)
dataframe_expandido

              titulo tempo_preparo  porcoes  total_ingredientes
0  Bolo de Chocolate    45 Minutos        8                   5
1             Salada    20 Minutos        4                   4
2     Salada Familia    40 Minutos        8                   4