### Exercício 6: Liste os produtos com preço maior que R$500.

In [5]:
import pandas as pd
import numpy as np

In [6]:
dataframe = pd.read_csv("dados/produtos.csv")
dataframe

   ID       Produto    Categoria  Preco  Quantidade
0   1      Notebook  Eletrônicos   3500           5
1   2         Mouse  Eletrônicos     80          30
2   3       Teclado  Eletrônicos    150          20
3   4       Cadeira       Móveis    600          10
4   5          Mesa       Móveis    900           7
5   6  Livro Python       Livros    120          15
6   7     Livro SQL       Livros    100          12

In [17]:
produtos_mais_caro = dataframe[dataframe["Preco"] > 500]
produtos_mais_caro

   ID   Produto    Categoria  Preco  Quantidade
0   1  Notebook  Eletrônicos   3500           5
3   4   Cadeira       Móveis    600          10
4   5      Mesa       Móveis    900           7