### Exercício 3: Exiba apenas as colunas Produto e Preco

In [1]:
import pandas as pd

In [2]:
dataframe = pd.read_csv("dados/produtos.csv")
dataframe

   ID       Produto    Categoria  Preco  Quantidade
0   1      Notebook  Eletrônicos   3500           5
1   2         Mouse  Eletrônicos     80          30
2   3       Teclado  Eletrônicos    150          20
3   4       Cadeira       Móveis    600          10
4   5          Mesa       Móveis    900           7
5   6  Livro Python       Livros    120          15
6   7     Livro SQL       Livros    100          12

In [19]:
collumns_produto_preco = dataframe[["Produto","Preco"]]
collumns_produto_preco

        Produto  Preco
0      Notebook   3500
1         Mouse     80
2       Teclado    150
3       Cadeira    600
4          Mesa    900
5  Livro Python    120
6     Livro SQL    100