### Exercício 17: Crie uma tabela de Categoria x Valor Total em Estoque.

In [2]:
import pandas as pd

In [3]:
dataframe = pd.read_csv("dados/produtos.csv")
dataframe

   ID       Produto    Categoria   Preco  Quantidade
0   1      Notebook  Eletrônicos  3500.0         5.0
1   2         Mouse  Eletrônicos    80.0        30.0
2   3       Teclado  Eletrônicos   150.0        20.0
3   4       Cadeira       Móveis   600.0        10.0
4   5          Mesa       Móveis   900.0         7.0
5   6  Livro Python       Livros   120.0        15.0
6   7     Livro SQL       Livros   100.0        12.0
7   8           NaN          NaN     NaN         NaN
8   9           NaN          NaN     NaN         NaN

In [5]:
dataframe["Valor Total em Estoque"] = dataframe["Preco"] * dataframe["Quantidade"]
dataframe

   ID       Produto    Categoria   Preco  Quantidade  Valor Total em Estoque
0   1      Notebook  Eletrônicos  3500.0         5.0                 17500.0
1   2         Mouse  Eletrônicos    80.0        30.0                  2400.0
2   3       Teclado  Eletrônicos   150.0        20.0                  3000.0
3   4       Cadeira       Móveis   600.0        10.0                  6000.0
4   5          Mesa       Móveis   900.0         7.0                  6300.0
5   6  Livro Python       Livros   120.0        15.0                  1800.0
6   7     Livro SQL       Livros   100.0        12.0                  1200.0
7   8           NaN          NaN     NaN         NaN                     NaN
8   9           NaN          NaN     NaN         NaN                     NaN

In [6]:
dataframe_estoque = dataframe.groupby("Categoria")["Valor Total em Estoque"].sum().reset_index()
dataframe_estoque

     Categoria  Valor Total em Estoque
0  Eletrônicos                 22900.0
1       Livros                  3000.0
2       Móveis                 12300.0