In [1]:
import pandas as pd

In [2]:
dados = {
    'Nome': ['Pedro', 'Antonio', 'Monalysa'],
    'Idade': [19, 20, 19],
    'Cidade': ['Paulista', 'Patos', 'Paulista']
}

In [3]:
df = pd.DataFrame(dados)
df

       Nome  Idade    Cidade
0     Pedro     19  Paulista
1   Antonio     20     Patos
2  Monalysa     19  Paulista

In [4]:
df.head(1)

    Nome  Idade    Cidade
0  Pedro     19  Paulista

In [5]:
df.tail(1)

       Nome  Idade    Cidade
2  Monalysa     19  Paulista

In [6]:
dados_notas = {
    'Nome': ['Pedro', 'Antonio', 'Monalysa'],
    'Matematica': [85, 90, 92],
    'Fisica': [91, 89, 97],
    'Quimica': [78, 81, 87]
}

In [7]:
df_notas = pd.DataFrame(dados_notas)
df_notas

       Nome  Matematica  Fisica  Quimica
0     Pedro          85      91       78
1   Antonio          90      89       81
2  Monalysa          92      97       87

In [13]:
# Calculando a media das notas
df_notas['Media'] = df_notas[['Matematica', 'Fisica', 'Quimica']].mean(axis=1)
df_notas

       Nome  Matematica  Fisica  Quimica      Media
0     Pedro          85      91       78  84.666667
1   Antonio          90      89       81  86.666667
2  Monalysa          92      97       87  92.000000

In [14]:
# Alunos com media maior que 90
alunos_notas_boas = df_notas[df_notas['Media'] >= 90]
alunos_notas_boas

       Nome  Matematica  Fisica  Quimica  Media
2  Monalysa          92      97       87   92.0

In [18]:
df_notas[['Nome', 'Media']]

       Nome      Media
0     Pedro  84.666667
1   Antonio  86.666667
2  Monalysa  92.000000

In [19]:
df_notas['MediaExatas'] = df_notas[['Matematica', 'Fisica']].mean(axis=1)
df_notas

       Nome  Matematica  Fisica  Quimica      Media  MediaExatas
0     Pedro          85      91       78  84.666667         88.0
1   Antonio          90      89       81  86.666667         89.5
2  Monalysa          92      97       87  92.000000         94.5