In [2]:
import pandas as pd

### Definindo os Dados

In [3]:
dict_metrics = {
    "idade": [15, 18, 25, 26, 40, 40, 58, 60],
    "altura": [160, 165, 149, 168, 172, 174, 174, 178]
}

In [4]:
type(dict_metrics)

dict

In [5]:
dataframe = pd.DataFrame(dict_metrics)
dataframe

   idade  altura
0     15     160
1     18     165
2     25     149
3     26     168
4     40     172
5     40     174
6     58     174
7     60     178

### Medidas de Posicao

- Media: Soma de todos os valores dividida pelo numero de valores. Pode ser sensivel a valores extremos
- Mediana: E o valor do meio quando os dados estao ordenados. Nao sofre por valores extremos
- Moda: Valor com a maior ocorrencia

In [6]:
media_idade = dataframe["idade"].mean()
media_altura = dataframe["altura"].mean()
print(f"Media de idades: {media_idade:.1f}")
print(f"Media de alturas: {media_altura:.1f}")

Media de idades: 35.2
Media de alturas: 167.5

In [7]:
mediana_idade = dataframe["idade"].median()
mediana_altura = dataframe["altura"].median()
print(f"Mediana de idades: {mediana_idade:.1f}")
print(f"Mediana de alturas: {mediana_altura:.1f}")

Mediana de idades: 33.0
Mediana de alturas: 170.0

In [8]:
moda_idade = dataframe["idade"].mode()
moda_altura = dataframe["altura"].mode()
print(f"Moda de idades: {moda_idade}")
print(f"Moda de alturas: {moda_altura}")

Moda de idades: 0    40
Name: idade, dtype: int64
Moda de alturas: 0    174
Name: altura, dtype: int64

### Medidas de Dispersão
- Variância: É a media dos quadrados entre cada valor e a media. Informa o quão distantes os valores estão da media.
- Desvio Padrão: É a raiz quadrada da Variância. Expressa a dispersão em termos da mesma unidade dos dados.
- Coeficiente de Variação: É o Desvio Padrão dividido pela media, expresso em porcentagem. Indica a variabilidade relativa dos dados em relação a media

In [9]:
variancia_idade = dataframe["idade"].var()
print(f"Variancia de idade: {variancia_idade}")

variancia_altura = dataframe["altura"].var()
print(f"Variancia de altura: {variancia_altura}")

Variancia de idade: 296.2142857142857
Variancia de altura: 88.57142857142857

In [10]:
desvio_padrao_idade = dataframe["idade"].std()
print(f"Desvio Padrao das idades: {desvio_padrao_idade}")

desvio_padrao_altura = dataframe["altura"].std()
print(f"Desvio Padrao das alturas: {desvio_padrao_altura}")

Desvio Padrao das idades: 17.210876959477854
Desvio Padrao das alturas: 9.411239481143202

In [11]:
coeficiente_variacao_idade = desvio_padrao_idade / media_idade * 100
print(f"coeficiente de variacao das idades: {coeficiente_variacao_idade:.2f}%")

coeficiente_variacao_altura = desvio_padrao_altura / media_altura * 100
print(f"coeficiente de variacao das alturas: {coeficiente_variacao_altura:.2f}%")

coeficiente de variacao das idades: 48.83%
coeficiente de variacao das alturas: 5.62%

### Medidas de Forma (Distribuição dos Dados)
- Assimetria: Indica o grau e direção da distorção da distribuição em relação à media. Se positiva, indica a cauda direita da distribuição mais longe, a oposta indica a cauda esquerda mais longa
- Curtose: Mede o pico ou "pontuação" da distribuição. Uma curtose alta indica uma distribuição mais concentreada, já o oposto indica uma distribuição mais achatada

In [12]:
dataframe

   idade  altura
0     15     160
1     18     165
2     25     149
3     26     168
4     40     172
5     40     174
6     58     174
7     60     178

In [13]:
assimetria_idade = dataframe["idade"].skew()
print(f"Assimetria das idades: {assimetria_idade}")

assimetria_altura = dataframe["altura"].skew()
print(f"Assimetria das alturas: {assimetria_altura}")

Assimetria das idades: 0.44254516049230713
Assimetria das alturas: -1.1359101638062434

##### Assimetria das idades positiva pois o valores maiores estao mais espalhados
##### Assimetria das alturas negativa pois o valores maiores estao mais proximos

In [14]:
curtose_idade = dataframe["idade"].kurtosis()
print(f"Curtose das idades: {curtose_idade}")

curtose_altura = dataframe["altura"].kurtosis()
print(f"Curtose das alturas: {curtose_altura}")

Curtose das idades: -1.3083027995345171
Curtose das alturas: 1.064502601456815

##### Curtose das idades negativa pois o dados sao mais espalhados
##### Curtose das alturas positiva pois o dados estao mais proximos da media

In [15]:
dataframe.describe()

           idade      altura
count   8.000000    8.000000
mean   35.250000  167.500000
std    17.210877    9.411239
min    15.000000  149.000000
25%    23.250000  163.750000
50%    33.000000  170.000000
75%    44.500000  174.000000
max    60.000000  178.000000

### Correlação
- Mede a relação entre duas variaveis, se positiva = diretamente proporcionais. Se negativa = inversamente proporcionais

### Índices de Correlação
- Coeficiente de Pearson: Mede a relação linear entre duas variaveis, variando de -1 a 1 e 0 para nenhuma correlação
- Coeficiente de Spearman: Util quando os dados nao tem uma relação linear clara ou quando as variaveis não são numericamente escalonaveis
- Pearson para relação liner e variaveis continuas e Spearman para relação não linear, ordinais ou com outliers

In [16]:
dataframe.corr(method="pearson")

           idade    altura
idade   1.000000  0.740852
altura  0.740852  1.000000

In [17]:
dataframe.corr(method="spearman")

           idade    altura
idade   1.000000  0.909639
altura  0.909639  1.000000

In [18]:
dataframe["idade"].corr(dataframe["altura"], method="pearson")

np.float64(0.7408519382898473)

In [19]:
dataframe["idade"].corr(dataframe["altura"], method="spearman")

np.float64(0.9096385542168675)